spring.datasource.url=mysql://root:hVgJZROTLdBeBsydLPNzaWiQSaTMLmFt@mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=hVgJZROTLdBeBsydLPNzaWiQSaTMLmFt


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
